### ISSUE TITLE
Improved collision and tryMove functionality

### ISSUE THREAD

**Issue by planetguy32** [DevelopersGuild/chamberslabyrinth#28]
We'll need a way to try to move a thing to a new position, but won't move it if there's something in the way.

Draft algorithm:
1. Create a rectangle enclosing the old and new positions completely
2. Test all possible collision boxes to see if they are inside the area
3. For each remaining rectangle, remove it from consideration if it is fully above or below the line travelled by a corner of the moving rectangle
4. Each remaining rectangle represents an obstacle. Check which side of the moving rectangle will hit it, and stop the movement at that point.

**Comment by vihanchaudhry** [comment]
These have already been implemented. tryMove is not required because basic move functions take care of the "try" part. Collision is now in the game, but we do not know if it is the most efficient way. Probably won't know for a while (until memory management becomes an issue, if it does).
