### ISSUE TITLE
Create room

### ISSUE THREAD

**Issue by irulenot** [DevelopersGuild/chamberslabyrinth#3]

**Comment by ghost** [comment]
@irulenot Go to bed!

**Comment by irulenot** [comment]
:)

**Comment by vihanchaudhry** [comment]
B-b-but all the real work gets done at night.

**Comment by ghost** [comment]
True :octocat: I made 30 commits today to one of my projects. So productive :+1:

**Comment by vihanchaudhry** [comment]
Room exists now. Nothing in there yet.
