### ISSUE TITLE
[Minor issue] Entity class does not have a virtual destructor

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#31]
Not a big deal, just a convention issue that could potentially make debugging a pain. Entity is an abstract class, and therefore needs a virtual destructor. This is especially important since we will potentially be deleting enemy and hero objects (or pointers) repeatedly.

**Comment by HiDaN4** [comment]
Fixed

**Comment by vihanchaudhry** [comment]
Wow! Thanks for the quick response Dmitry :)
But we must remember to actually put stuff in the hero and enemy1/enemy2/... destructors at some point. The final derived classes need non-virtual destructors so that when we call delete, they do all the work for us. It will make death and respawning easier.

**Comment by HiDaN4** [comment]
No problem)

Right now, we don't perform any allocation in enemy/hero classes, so there is nothing to delete, right?

I believe that when you derive a class, its destructor is automatically virtual, but it is a good idea to write the prefix just as a reminder.

**Comment by vihanchaudhry** [comment]
Yes it is just a convention thing. Just like you always initialize global variables to 0 manually even though they already do that.

**Comment by HiDaN4** [comment]
Actually, it depends on the compiler, and in some occasion int can be 0xffff or whatever; thus, it's better to initialize all variables to 0.

I remember I had one problem of getting a random number for a variable while processing it, and it took quite a lot to realize that I had not set it to 0)
