### ISSUE TITLE
Modifying temporary const vector pointer in Hero.cpp

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#46]
What is going on in the Hero.cpp update function? It's a mess of temporary constant vector pointers. Line 127 starts a for loop that modifies a temporary const vector. Why? 
It is extremely confusing to read and there are no comments. 
Whoever wrote it, please look it over and fix the for loop, or find another way to write the same code. It won't compile on Xcode.

**Comment by vihanchaudhry** [comment]
Edwin:
GitHub is only showing me the commit on which the code was moved on your commit. I can't find where it was originally added. 
I'm assigning you to this for now, even if it wasn't you (not sure who wrote it though, doesn't really matter)
Something in the code is redundant.

Not blaming anyone. It's no big deal. I just want our code to remain cross-platform like it has so far.

**Comment by AngkasaEdwin** [comment]
It was there before I added my change. The loop is just to check the current effects the hero has at the moment (details in effects.h and cpp). This loop only covers the speed buff though. I'll look at it when I get home.

**Comment by AngkasaEdwin** [comment]
Changed the loop to iterate using array notation (+comments).

**Comment by vihanchaudhry** [comment]
Thank you for the response and the fix, Edwin! :D
