### ISSUE TITLE
[Concept] Game design direction decision

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#56]
We need to decide what the general theme is. A few things need to happen for this:
- We need a basic reason for why the hero is in a dungeon.
- We need a little intro comic strip to explain that reason before the game starts (this is our "cutscene") in true indie game fashion.
- WE NEED A NAME ALREADY, CHAMBER'S LABYRINTH MAKES NO SENSE

**Comment by AngkasaEdwin** [comment]
First draft for the storyline is under docs
