### ISSUE TITLE
Project: Transition

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#58]
This is a big one. It involves a lot of things and it will determine our game's core progression. 

These are the things it needs:
- Completion Condition: When does a map end? When everything is dead (at least for now)
- Progression: How many maps till a boss fight? How random is it? (e.g. Beating one map gives a 15% chance for the next map to be a boss fight, beating four maps gives a 65% chance for the next map to be a boss fight, etc.)
- Doors: How to move on to the next map? Doors on bottom corners, sometimes sky-doors on top corner, etc.
- Scaling: After how many boss fights/maps does the game scale up in difficulty?

**Comment by AngkasaEdwin** [comment]
Doors are now functional. We may proceed to one of the stages in the level template. We can now work on the progression.

**Comment by vihanchaudhry** [comment]
Completion condition is sufficient for now (maybe forever).
Doors are good. 
Progression is the next immediate focus, with scaling being worked on side-by-side (preferably by the same person).

**Comment by AngkasaEdwin** [comment]
Boss stage is now accessible. A cropped version of tempBoss used and its damaging boundary box is set. Spear dmg is changed to 200 for testing purpose. Check it out!

**Comment by vihanchaudhry** [comment]
Scaling moved to a new issue. Everything else is done.

**Comment by vihanchaudhry** [comment]
Thanks @AngkasaEdwin and @RuiLi280.
