### ISSUE TITLE
Arrow keys don't work on Retina MacBook

### ISSUE THREAD

**Issue by pmer** [DevelopersGuild/chamberslabyrinth#63]
Chris Banh's arrow keys don't cause the player to move.

**Comment by vihanchaudhry** [comment]
@jamer There has got to be another common factor for which machines cause this issue. Do you know of any ways to test/replicate this issue? It seems like it would be an easy fix if we can track it down.

**Comment by pmer** [comment]
@vihanchaudhry I don't know any other computers that experience this issue.  But I also don't know another person with a Retina MacBook so I was just guessing that was even the issue in the first place.

I hesitate to ask Chris for his laptop so I can look at it... :-(

**Comment by vihanchaudhry** [comment]
This turned out to be a Chris-only issue.
