### ISSUE TITLE
Xcode project icon was lost during name change migration process

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#64]
@jamer I'm not sure how you did the first time...

**Comment by pmer** [comment]
First you go the project and you click the right-arrow next to App Icons - Source.

![project](https://cloud.githubusercontent.com/assets/107998/7698619/9c964f00-fdc6-11e4-859f-2635e333e2f8.png)

Then you drag-and-drop your images into place for the different sizes.  In this case we'll just use a 128x128 image of the reaper.

![editor](https://cloud.githubusercontent.com/assets/107998/7698621/9e980a00-fdc6-11e4-9c9c-fd35f79d3d94.png)

**Comment by pmer** [comment]
I've fixed the issue with 4f5900d4048c9dcf979c90001ec0e6cb22acfa18 and pushed the fix to development.
