### ISSUE TITLE
Sometimes when jumping the hero moves right rapidly when hitting the ground

### ISSUE THREAD

**Issue by pmer** [DevelopersGuild/chamberslabyrinth#65]
It happens about 2-5% of the time on a jump.

When you start moving right it goes very quick and you move off the map in less than a second.  You die shortly thereafter.

**Comment by vihanchaudhry** [comment]
Yes I noticed this one. I'm inclined to believe the hero's bounding box has something to do with it. Still trying to track it down.

**Comment by vihanchaudhry** [comment]
Hero can no longer go inside of ground platforms.
