### ISSUE TITLE
[MAJOR] Gameplay is not rewarding

### ISSUE THREAD

**Issue by vihanchaudhry** [DevelopersGuild/chamberslabyrinth#68]
Lack of fluidity makes the gameplay less fun. 
- When you attack enemies, you are frozen but the enemies don't get knocked back far enough and long enough, so you get hit anyway.

**Comment by pmer** [comment]
It's hard to dodge enemy attacks, so I lose a lot of health.  But I don't get a lot of health back.

**Comment by vihanchaudhry** [comment]
Getting better, damage numbers and faster attack time have made the game a lot more fun. Enemy animations, audiovisual hit cues, and jump attacking should make it a lot more fun.

**Comment by vihanchaudhry** [comment]
Leaving the rest as separate issues.
