### ISSUE TITLE
Project: Boss dialog

### ISSUE THREAD

**Issue by pmer** [DevelopersGuild/chamberslabyrinth#79]
# Context

The plot of the game is that the player is a wraith, just like the enemies, but he does not realize it because to acknowledge it would result in an inner conflict within him.
# Cinematic effect

When he gets to the boss, a small cinematic plays.  The player and the boss will have a short dialog during which the game is paused.

Boss: “You are one of us.  You even look like one of us.”

Player: “I look nothing like you.”

Boss: “You are and you just don’t see it yet.”

After the three lines are shown, the game resumes.

While the game is paused and dialog is onscreen, only two keyboard buttons work:
- `Escape` quits the game. (Like usual)
- `Spacebar` continues to the next line of dialog.

Each line of dialog stays onscreen until the user presses Spacebar.  They do not disappear with merely a timer.  This lets a player pause and read the text once or twice while thinking about it.
# Implementation

To implement the above, create three new `GameState`s:
- bossText1
- bossText2
- bossText3

When the player enters the boss room for the first time, switch the game state to bossText1.  In bossText1, the player and boss and background and platforms, etc, are drawn normally, just like inGame state.  No game updates happen, though.

Additionally, a PNG or JPG is draw to the screen, probably centered (or whatever looks good) with some pre-rendered text on it.  The pre-rendered text should say one of the three lines above.

**Comment by AngkasaEdwin** [comment]
There's an issue where pressing and releasing spacebar count as 2 key presses. Parts of the dialogue are skipped because of this. Can somebody fix this?

**Comment by vihanchaudhry** [comment]
@AngkasaEdwin This sounds like a familiar bug I've run into before. I can't remember when I dealt with this, but I believe it was quite long ago. It has to do with how the game states work. I'll look into it. Thanks!

**Comment by AngkasaEdwin** [comment]
The text position is messed up because the hero spawns randomly in the map. Where is the part of the code that does this?

**Comment by AngkasaEdwin** [comment]
@vihanchaudhry Ok! I'll work on #85 and #87 for now
