### ISSUE TITLE
New title screen

### ISSUE THREAD

**Issue by pmer** [DevelopersGuild/chamberslabyrinth#81]
Stretch dungeonbrickwindow.png across the background.

Show title "WRAITHKEEPER'S TOMB" at bottom right.

Show menu items "PLAY" and "EXIT" on top left.

**Comment by pmer** [comment]
![img_20150527_170258](https://cloud.githubusercontent.com/assets/107998/7850123/7ea2b84e-0492-11e5-9379-3d2167158fcd.jpg)

**Comment by vihanchaudhry** [comment]
Done.
