### ISSUE TITLE
Game closes when you hit enter during boss dialog

### ISSUE THREAD

**Issue by pmer** [DevelopersGuild/chamberslabyrinth#91]
The game quits when you hit the Enter key during the boss dialog.

Platform: Mac
# Steps to reproduce
1. Get to the boss
2. Hit "Enter" key on the first dialog screen
3. See that the game quits
# Expected behavior

The game goes to the next dialog screen.

**Comment by CrispyMango** [comment]
Can someone please take me off the list, I'm not even part of this project?
Please and thank you

**Comment by pmer** [comment]
@CrispyMango: Done! :) Take care!

**Comment by AngkasaEdwin** [comment]
Fixed!
